package com.sunny.jobboard.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Entity
// Composite Unique Constraint
// One candidate can only apply to the same job ONCE
// This is enforced at the DB level — not just in service code
@Table(
        name = "applications",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"job_id", "candidate_id"})
        }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Application {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "job_id", nullable = false)
    private Job job;

    @ManyToOne(fetch =  FetchType.LAZY)
    @JoinColumn(name = "candidate_id", nullable = false)
    private User candidate;

    // Cloudinary URL of the uploaded PDF resume
    @Column(nullable = false)
    private String resumeUrl;

    @Column(columnDefinition = "TEXT")
    private String coverLetter;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private ApplicationStatus status = ApplicationStatus.PENDING;

    // AI-generated match score (0-100), set after analysis
    private Integer aiMatchScore;

    @Column(columnDefinition = "TEXT")
    private String aiMatchSummary;

    @Column(nullable = false, updatable = false)
    private LocalDateTime appliedAt;

    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        appliedAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}

//🔖 JPA Concept — @UniqueConstraint
//Enforces that (job_id + candidate_id) combination
//must be unique across the table.
//This means: one candidate cannot apply to the same
//job twice — even if the service code has a bug.
//DB-level constraints are your last line of defense.
//
//Difference from @Column(unique=true):
//@Column(unique=true)     → unique on ONE column
//@UniqueConstraint        → unique on COMBINATION of columns
//
//🔖 New fields for AI:
//aiMatchScore   → 0-100 score generated by Claude
//aiMatchSummary → text explanation of why the score
//Both are nullable — set only when ADMIN triggers analysis